---

- name: Ensure SSSD is started and enabled on boot
  service:
    name:    '{{ sssd__service_name }}'
    enabled: '{{ sssd__service_enabled|bool }}'
    state:   "{{ sssd__service_enabled|bool|ternary('started', 'stopped') }}"
